name: Release

on:
  push:
    tags:
      - "v*"

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  package:
    name: Package on ${{ startsWith(matrix.os, 'macos-') && 'macOS' || startsWith(matrix.os, 'windows-') && 'Windows' || 'Linux' }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install project
        run: pip install -e .

      - name: Install playwright
        env:
          PLAYWRIGHT_BROWSERS_PATH: 0
        run: python -m playwright install --with-deps chromium

      - name: Install pyinstaller
        run: pip install --upgrade pyinstaller

      - name: Build package
        run: pyinstaller --onefile --clean --name fms-event-monitor ./src/fms_event_monitor/__main__.py

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: fms-event-monitor-{{ matrix.os }}
          path: dist/fms-event-monitor${{ startsWith(matrix.os, 'windows-') && '.exe' || '' }}
